.\" Process this file with
.\" groff -man -Tascii easyirc.1
.\"
.TH EASYIRC 1 "NOVEMBER 2013" Linux "User Manuals"
.SH NAME
easyirc \- command line interface for IRC
.SH SYNOPSIS
.B easyirc client [-x]
.br
.B easyirc connect -i | --interactive [
.I options
.B ...]
.br
.B easyirc connect [-q | -v] [-x] -H
.I host
.B [-P
.I port
.B ] -N
.I nick
.B [-I
.I ident
.B ] [-R
.I realname
.B ] [-L
.I channel
.B [-K
.I keyword
.B ]] [-F
.I file
.B [-B] | -C
.I cmd
.B [-A
.I args
.B ]]
.br
.B easyirc command [-q | -v] [-x]
.I <file> <cmd> <args>
.br
.B easyirc {connect | command} -h | --help
.SH DESCRIPTION
.B easyirc
provides a command line interface for IRC chatting and IRC bots.
.br
To chat normally using easy irc, use
.B easyirc client
\.
.br
To send a one-of IRC command, use
.B easyirc connect -H
.I host
.B -N
.I nick
.B -C
.I cmd
.B [-A
.I args
.B ]
\.  Optionally, use
.B -F
.I file
to specify a file where each line is a single command with its arguments
that should be executed.
.br
To start an irc bot, use
.B easyirc connect -H
.I host
.B -N
.I nick
.B -F
.I filename
.B -B &
, then commands can be sent to the bot either by using normal file
output like
.B echo "/join #MyChannel superSecretPassword" >
.I filename
to send a pre-formatted command; or by running EasyIrc in command mode
to format your command -- example:
.br
.B easyirc command
.I filename
.B join MyChannel superSecretPassword
.SH OPTIONS
TODO
