#line 2 "../src/parser/lexer.cxx"

#line 4 "../src/parser/lexer.cxx"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cpp_yy_create_buffer
#define yy_delete_buffer cpp_yy_delete_buffer
#define yy_flex_debug cpp_yy_flex_debug
#define yy_init_buffer cpp_yy_init_buffer
#define yy_flush_buffer cpp_yy_flush_buffer
#define yy_load_buffer_state cpp_yy_load_buffer_state
#define yy_switch_to_buffer cpp_yy_switch_to_buffer
#define yyin cpp_yyin
#define yyleng cpp_yyleng
#define yylex cpp_yylex
#define yylineno cpp_yylineno
#define yyout cpp_yyout
#define yyrestart cpp_yyrestart
#define yytext cpp_yytext
#define yywrap cpp_yywrap
#define yyalloc cpp_yyalloc
#define yyrealloc cpp_yyrealloc
#define yyfree cpp_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cpp_yyrestart(cpp_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t cpp_yyleng;

extern FILE *cpp_yyin, *cpp_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cpp_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cpp_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cpp_yyrestart()), so that the user can continue scanning by
	 * just pointing cpp_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cpp_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t cpp_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cpp_yywrap()'s to do buffer switches
 * instead of setting up a fresh cpp_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cpp_yyrestart (FILE *input_file  );
void cpp_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cpp_yy_create_buffer (FILE *file,int size  );
void cpp_yy_delete_buffer (YY_BUFFER_STATE b  );
void cpp_yy_flush_buffer (YY_BUFFER_STATE b  );
void cpp_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cpp_yypop_buffer_state (void );

static void cpp_yyensure_buffer_stack (void );
static void cpp_yy_load_buffer_state (void );
static void cpp_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cpp_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cpp_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cpp_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cpp_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *cpp_yyalloc (yy_size_t  );
void *cpp_yyrealloc (void *,yy_size_t  );
void cpp_yyfree (void *  );

#define yy_new_buffer cpp_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cpp_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cpp_yy_create_buffer(cpp_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cpp_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cpp_yy_create_buffer(cpp_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cpp_yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cpp_yyin = (FILE *) 0, *cpp_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int cpp_yylineno;

int cpp_yylineno = 1;

extern char *cpp_yytext;
#define yytext_ptr cpp_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cpp_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cpp_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[260] =
    {   0,
        0,    0,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,    0,    0,    0,    0,   39,   39,
       65,   63,    3,    1,   56,   15,   52,   57,   53,   63,
       63,   59,   60,   63,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   18,   16,   64,   18,   21,   19,
       20,   23,   16,   22,   25,   16,   24,   40,   26,   28,
       16,   27,   38,   37,   38,   38,   39,    3,    1,    1,
        2,    0,    0,    0,    0,    0,    0,    0,   61,   54,
       55,   61,    0,   60,   60,   60,   51,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   18,

       18,   16,   18,   21,   21,   22,   24,   26,   27,   37,
        0,    0,    0,    0,    0,    0,   39,    2,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   55,   62,   62,
       62,   49,   62,   62,   62,   62,   62,   62,   62,   62,
       18,    0,    0,   29,    0,    0,   33,    0,    0,    0,
        0,    6,    0,    0,    0,    0,    0,    0,    0,   61,
       62,   45,   62,   62,   62,   62,   62,   62,   58,   62,
       62,   17,    0,    0,    0,   29,    0,    0,    0,   33,
        0,   12,   11,    0,    0,    0,    0,    0,    0,    0,
       46,   62,   62,   62,   62,   62,   62,   62,   17,   17,

        0,   30,    0,    0,   34,    0,    0,   12,   11,   13,
        0,    0,    0,    0,    0,    0,   62,   62,   62,   42,
       47,   62,   62,   31,   30,   32,   35,   34,   36,    0,
       13,    7,    0,    0,    0,   10,    0,   62,   44,   62,
       48,   62,   32,   35,   35,   36,    9,    8,    0,    4,
        0,   62,   62,   50,    5,   14,   41,   43,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    8,    9,    1,
        1,   10,   11,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
        1,    1,    1,    1,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   20,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   18,    1,   21,   22,   23,   24,

       25,   26,   27,   18,   28,   18,   18,   29,   30,   31,
       32,   33,   18,   34,   35,   36,   37,   38,   39,   18,
       40,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[41] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[289] =
    {   0,
        0,    0,   39,   43,   47,   52,   75,    0,  115,    0,
      155,    0,  195,    0,   40,   53,   56,   58,  563,  562,
      564,  567,   68,  234,  567,  238,  567,  567,  567,   52,
      228,  230,  234,  547,    0,  533,  530,  539,  528,  537,
      213,  521,   28,  525,  250,  251,  567,  255,  259,  567,
      567,  567,  265,    0,  567,  267,    0,  567,    0,  567,
      276,    0,  567,    0,  277,  278,    0,  283,  552,  287,
        0,    0,  529,  262,  242,  519,  521,  530,  282,  567,
        0,  285,  297,  301,  305,  567,  567,    0,  529,  512,
      519,  511,  516,  266,  523,  510,  506,  509,  506,  321,

        0,  322,  326,  327,    0,    0,    0,    0,    0,    0,
      332,  307,  514,  337,  312,  513,    0,    0,  512,  223,
      513,  343,  513,  514,  510,  499,  336,    0,  497,  501,
      495,    0,  504,  490,  491,  497,  488,  499,  498,  494,
      350,  318,  497,    0,  326,  496,    0,  491,  492,  492,
      488,  354,  490,  490,  484,  485,  486,  479,  349,  354,
      474,    0,  483,  472,  485,  480,  476,  480,    0,  478,
      474,  368,  474,  474,  470,    0,  471,  471,  467,    0,
      463,    0,    0,  467,  466,  466,  453,  459,  461,  456,
        0,  448,  442,  452,  449,  433,  441,  432,  374,    0,

      375,  330,  434,  376,    0,  431,  429,    0,    0,    0,
      380,  425,  424,  424,  381,  411,  418,  411,  397,    0,
        0,  388,  347,  382,  335,    0,  386,    0,    0,  387,
        0,  388,  392,  333,  393,  394,  303,  299,    0,  293,
        0,  290,    0,    0,  398,    0,  399,  400,  404,  405,
      406,  283,  271,    0,  410,  411,    0,    0,  567,  416,
      419,  422,  425,  428,  281,  431,  434,  271,  256,   71,
       48,  437,  440,  443,  446,  449,  452,  455,  458,  461,
      464,  467,  470,  473,  476,  479,  482,  485
    } ;

static yyconst flex_int16_t yy_def[289] =
    {   0,
      259,    1,  260,  260,  261,  261,  259,    7,  259,    9,
      259,   11,  259,   13,  262,  262,  262,  262,  263,  263,
      259,  259,  259,  264,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  266,  259,  259,  266,  267,  259,
      259,  259,  259,  268,  259,  259,  269,  259,  270,  259,
      259,  271,  259,  272,  259,  259,  273,  259,  264,  264,
      274,   26,  259,  259,  259,  259,  259,  259,  259,  259,
      275,  259,  259,  259,  259,  259,  259,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  266,

      276,  259,  266,  267,  277,  268,  269,  270,  271,  272,
      259,  259,  259,  259,  259,  259,  273,  274,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  275,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      266,  259,  259,  278,  259,  259,  279,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  280,  259,  259,  259,  278,  259,  259,  259,  279,
      259,  281,  282,  259,  259,  259,  259,  259,  259,  259,
      265,  265,  265,  265,  265,  265,  265,  265,  280,  283,

      259,  259,  259,  259,  284,  259,  259,  281,  282,  285,
      259,  259,  259,  259,  259,  259,  265,  265,  265,  265,
      265,  265,  265,  259,  259,  286,  287,  284,  288,  259,
      285,  259,  259,  259,  259,  259,  259,  265,  265,  265,
      265,  265,  286,  287,  287,  288,  259,  259,  259,  259,
      259,  265,  265,  265,  259,  259,  265,  265,    0,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259
    } ;

static yyconst flex_int16_t yy_nxt[608] =
    {   0,
       22,   23,   24,   23,   23,   25,   26,   27,   28,   29,
       22,   30,   31,   32,   33,   34,   22,   35,   35,   35,
       35,   35,   36,   35,   37,   38,   35,   39,   35,   35,
       40,   35,   41,   35,   42,   43,   44,   35,   35,   35,
       46,   47,   64,   46,   46,   47,   65,   46,   46,   47,
      109,   46,   50,   46,   47,   64,   46,   50,   64,   65,
       64,   97,   66,   51,   66,   79,   79,   98,   51,   68,
       48,   68,   68,  108,   48,   52,   53,   47,   52,   53,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   55,   56,   47,   55,   56,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   58,   46,   47,   58,   46,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   60,   61,   47,   60,   61,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   70,   71,   80,   70,   72,
       81,   82,   72,   83,   83,   82,   94,   84,   85,   95,
      149,  101,  102,   86,  101,  102,  101,  150,  107,  101,
      105,   73,   74,  105,  105,   75,  102,  122,  102,  102,
       76,  102,  123,  106,   77,  105,   78,  102,  111,  114,
      102,  111,  114,   88,   68,  103,   68,   68,   70,   71,
      120,   70,  121,  134,  258,   79,   79,  135,   79,   79,

      127,  112,  115,  127,  113,  116,  127,  257,   82,  127,
       83,   83,   82,  254,   84,   84,   82,  253,   84,   85,
       86,  252,  101,  102,   86,  101,  102,  101,  105,  251,
      101,  105,  105,  111,  225,  142,  111,  143,  114,  225,
      145,  114,  146,  105,  152,  173,  159,  152,  141,  160,
      160,  101,  174,  177,  101,  152,  112,  249,  152,  113,
      178,  115,  160,  160,  116,  225,  153,  160,  160,  200,
      225,  242,  200,  154,  172,  200,  224,  227,  200,  224,
      227,  232,  236,  224,  232,  236,  224,  245,  247,  232,
      245,  247,  232,  248,  250,  236,  248,  250,  236,  245,

      247,  248,  245,  247,  248,  255,  250,  256,  255,  250,
      256,  255,  256,  241,  255,  256,   45,   45,   45,   49,
       49,   49,   63,   63,   63,   67,   67,   67,   69,   69,
       69,  100,  240,  100,  104,  239,  104,  110,  238,  110,
      117,  237,  117,  118,  235,  118,  128,  234,  128,  101,
      233,  101,  105,  230,  105,  176,  229,  176,  180,  226,
      180,  199,  223,  199,  208,  222,  208,  209,  221,  209,
      200,  220,  200,  228,  219,  228,  231,  218,  231,  243,
      217,  243,  244,  216,  244,  246,  215,  246,  214,  213,
      212,  211,  210,  207,  206,  205,  204,  203,  202,  201,

      198,  197,  196,  195,  194,  193,  192,  169,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  179,
      175,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  158,  157,  156,  155,  151,  148,  147,  144,
      140,  139,  138,  137,  136,  133,  132,  131,  130,  129,
      126,  125,  124,  119,  259,   99,   96,   93,   92,   91,
       90,   89,   87,  259,   47,   47,   21,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259
    } ;

static yyconst flex_int16_t yy_chk[608] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,   15,    3,    4,    4,   15,    4,    5,    5,
      271,    5,    5,    6,    6,   16,    6,    6,   17,   16,
       18,   43,   17,    5,   18,   30,   30,   43,    6,   23,
        3,   23,   23,  270,    4,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   24,   24,   31,   24,   26,
       31,   32,   26,   32,   32,   33,   41,   33,   33,   41,
      120,   45,   46,   33,   45,   46,   48,  120,  269,   48,
       49,   26,   26,   49,   49,   26,   53,   75,   56,   53,
       26,   56,   75,  268,   26,   49,   26,   61,   65,   66,
       61,   65,   66,  265,   68,   48,   68,   68,   70,   70,
       74,   70,   74,   94,  253,   79,   79,   94,   82,   82,

       79,   65,   66,   82,   65,   66,   79,  252,   83,   82,
       83,   83,   84,  242,   84,   84,   85,  240,   85,   85,
       84,  238,  100,  102,   85,  100,  102,  103,  104,  237,
      103,  104,  104,  111,  202,  112,  111,  112,  114,  225,
      115,  114,  115,  104,  122,  142,  127,  122,  103,  127,
      127,  141,  142,  145,  141,  152,  111,  234,  152,  111,
      145,  114,  159,  159,  114,  202,  122,  160,  160,  172,
      225,  223,  172,  122,  141,  199,  201,  204,  199,  201,
      204,  211,  215,  224,  211,  215,  224,  227,  230,  232,
      227,  230,  232,  233,  235,  236,  233,  235,  236,  245,

      247,  248,  245,  247,  248,  249,  250,  251,  249,  250,
      251,  255,  256,  222,  255,  256,  260,  260,  260,  261,
      261,  261,  262,  262,  262,  263,  263,  263,  264,  264,
      264,  266,  219,  266,  267,  218,  267,  272,  217,  272,
      273,  216,  273,  274,  214,  274,  275,  213,  275,  276,
      212,  276,  277,  207,  277,  278,  206,  278,  279,  203,
      279,  280,  198,  280,  281,  197,  281,  282,  196,  282,
      283,  195,  283,  284,  194,  284,  285,  193,  285,  286,
      192,  286,  287,  190,  287,  288,  189,  288,  188,  187,
      186,  185,  184,  181,  179,  178,  177,  175,  174,  173,

      171,  170,  168,  167,  166,  165,  164,  163,  161,  158,
      157,  156,  155,  154,  153,  151,  150,  149,  148,  146,
      143,  140,  139,  138,  137,  136,  135,  134,  133,  131,
      130,  129,  126,  125,  124,  123,  121,  119,  116,  113,
       99,   98,   97,   96,   95,   93,   92,   91,   90,   89,
       78,   77,   76,   73,   69,   44,   42,   40,   39,   38,
       37,   36,   34,   21,   20,   19,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cpp_yy_flex_debug;
int cpp_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cpp_yytext;
#line 1 "../src/parser/lexer.lxx"
/* Filename: lexer.lxx */
#line 4 "../src/parser/lexer.lxx"
	#include "lexer.h"
	#include "parser.h"
	#include "parser.dxx"

	#include "cpp.h"
	#include "preprocess/preparser.h"

	#include <cctype>        // isxdigit
	#include <iostream>      // std::cerr, std::ostream
	#include <deque>         // std::deque

	#define yylval cpp_yylval
	#define yylloc cpp_yylloc
	#define yyerror cpp_yyerror
	#define yywarning cpp_yywarning
	#define YY_DECL int cpp_yylex(void)
	using namespace std;


	/* Struct Definitions */
	// An Input holds extra per-file information while lexing and parsing
	struct Input : File
	{
		Input(const string& name = "<???>");

		string current_line; // holds the current line for error reporting
		list<string> comments;
		int line_number; // current line of the input
		int col_number; // current col of the input
		int times_included; // number of times the file has been included
		int condition_depth; // depth of #if statements
	};

	/* Lexer State */
	static int error_count;
	static int warning_count;
	static deque<Input*> inputs;
	static Module* current_module = NULL;
	#define macros (current_module->macros)
	#define files (current_module->files)

	#define echo() \
		cout << "Token(" << inputs.front()->name << "): " << cpp_yytext << "\n"
	#define echo_location()\
		cout << "(in file " << inputs.front()->name << " at line " << inputs.front()->line_number << ").\n";

	/* Function Declarations */
	// emit outputs the specified token from the lexer with location information
	#define emit(token)                                        \
		yylloc.last_line = inputs.front()->line_number;        \
		yylloc.last_column = inputs.front()->col_number;       \
		if(!inputs.front()->comments.back().empty()) {         \
			yylloc.comment = &inputs.front()->comments.back(); \
			inputs.front()->comments.push_back("");            \
		}                                                      \
		return token
		
	// accept is called below when receiving a regex from the lexer;
	//     it increments the current column number, and sets some location information
	static void accept();

	// accept_include is an alternate accepts that handles the #include directive;
	//     returns if there was an error with the include.
	static bool accept_include(char end_mark);

	// peek_char returns the character that will be returned in
	//     the next call to read_char.
	inline int peek_char();

	// read_char reads and returns a single character,
	//     incrementing the line and column numbers as appropriate.
	inline int read_char();
	static int read_char(int & line, int & col);

	// todo: doc
	inline char read_char_const(bool auto_escape = false);
	static char read_char_const(int & line, int & col, bool auto_escape = false);

	// todo: doc
	static void scan_define(const string& identifier);
	static string scan_if();
	static string scan_block_comment();
	static string scan_string_literal(char quote_mark = '"');
/* Flex Options */
/* Lexer States */









/* Regex Definitions */
/*"/*
// These regexs are correct to the specification, but we're using simplified
//     versions until someone feels the need to implement them.

HEXNUM_LITERAL  (0x[0-9a-fA-F]*([uU](l|L|ll|LL)?|(l|L|ll|LL)[uU]?)?)
BINARY_LITERAL  (0[bB][01]+([uU](l|L|ll|LL)?|(l|L|ll|LL)[uU]?)?)
DECIMAL_LITERAL ([1-9]+[0-9]*([uU](l|L|ll|LL)?|(l|L|ll|LL)[uU]?)?)
FLOATING_POINT  ((([0-9]+[.])|([0-9]*[.][0-9]+))([eE][+-]?[0-9]+)?[lLfF]?)
OCTAL_LITERAL   (0[0-7]*([uU](l|L|ll|LL)?|(l|L|ll|LL)[uU]?)?)
*/
#line 802 "../src/parser/lexer.cxx"

#define INITIAL 0
#define pragma 1
#define include 2
#define ifdef 3
#define ifndef 4
#define define 5
#define undef 6
#define elseif 7
#define endif 8
#define warning 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cpp_yylex_destroy (void );

int cpp_yyget_debug (void );

void cpp_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE cpp_yyget_extra (void );

void cpp_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cpp_yyget_in (void );

void cpp_yyset_in  (FILE * in_str  );

FILE *cpp_yyget_out (void );

void cpp_yyset_out  (FILE * out_str  );

yy_size_t cpp_yyget_leng (void );

char *cpp_yyget_text (void );

int cpp_yyget_lineno (void );

void cpp_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cpp_yywrap (void );
#else
extern int cpp_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cpp_yytext, cpp_yyleng, 1, cpp_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cpp_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cpp_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cpp_yyin))==0 && ferror(cpp_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cpp_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cpp_yylex (void);

#define YY_DECL int cpp_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cpp_yytext and cpp_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 123 "../src/parser/lexer.lxx"


#line 1006 "../src/parser/lexer.cxx"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cpp_yyin )
			cpp_yyin = stdin;

		if ( ! cpp_yyout )
			cpp_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cpp_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cpp_yy_create_buffer(cpp_yyin,YY_BUF_SIZE );
		}

		cpp_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cpp_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 567 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 125 "../src/parser/lexer.lxx"
{
	// New line.  Save a copy of the line so we can print it out for the
	// benefit of the user in case we get an error.

	inputs.front()->current_line = cpp_yytext+1;
	inputs.front()->line_number++;
	inputs.front()->col_number = 0;

	// Return the whole line to the lexer, except the newline character, which we eat.
	yyless(1);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 137 "../src/parser/lexer.lxx"
{
	// An empty line will clear our current comment
	// This option overrides (\n.*) because it produces a longer output
	if(!inputs.front()->comments.back().empty()) {
		inputs.front()->comments.push_back("");
	}

	inputs.front()->current_line = cpp_yytext+2;
	inputs.front()->line_number += 2;
	inputs.front()->col_number = 0;

	// Return the whole line to the lexer, except the newline characters, which we eat.
	yyless(2);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 152 "../src/parser/lexer.lxx"
{
	// Eat whitespace.
	accept();
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 157 "../src/parser/lexer.lxx"
{
	// Preprocessor #pragma directive
	accept();
	yy_push_state(pragma);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 163 "../src/parser/lexer.lxx"
{
	// Preprocessor #include directive
	accept();
	yy_push_state(include);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 169 "../src/parser/lexer.lxx"
{
	accept();

	inputs.front()->condition_depth++;
	string condition = scan_if();
	if(!parse_if_directive(current_module, condition)) {
		yy_push_state(elseif);
	} else {
		yy_push_state(INITIAL);
	}
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 181 "../src/parser/lexer.lxx"
{
	// Preprocessor #ifdef directive
	accept();
	yy_push_state(ifdef);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 187 "../src/parser/lexer.lxx"
{
	// Preprocessor #ifndef directive
	accept();
	yy_push_state(ifndef);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 193 "../src/parser/lexer.lxx"
{
	// Preprocessor #define directive
	accept();
	yy_push_state(define);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 199 "../src/parser/lexer.lxx"
{
	// Preprocessor #undef directive
	accept();
	yy_push_state(undef);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 205 "../src/parser/lexer.lxx"
{
	accept();
	if(!inputs.front()->condition_depth) {
		yyerror("Found #else without previous #if.");
	} else {
		yy_pop_state();
		yy_push_state(endif);
	}
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 215 "../src/parser/lexer.lxx"
{
	accept();
	if(!inputs.front()->condition_depth) {
		yyerror("Found #elif without previous #if.");
	} else {
		yy_pop_state();
		yy_push_state(endif);
	}
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 225 "../src/parser/lexer.lxx"
{
	// Preprocessor #endif directive
	accept();
	if(!inputs.front()->condition_depth) {
		yyerror("Found #endif without previous #if.");
	} else {
		inputs.front()->condition_depth--;
		yy_pop_state();
	}
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 236 "../src/parser/lexer.lxx"
{
	accept();
	yy_push_state(warning);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 241 "../src/parser/lexer.lxx"
{
	// Fail on all other preprocessor ops
	accept();
	yyerror("Treesap hasn't implemented this preprocessor directive yet.");

	// Consume the rest of the line, except the newline (\n) character
	int c = peek_char();
	while(c!= '\n' && c != EOF) {
		read_char();
		c = peek_char();
	}
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 254 "../src/parser/lexer.lxx"
{
	accept(); // eat whitespace everywhere
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 258 "../src/parser/lexer.lxx"
{
	accept();
	if(inputs.front()->times_included > 1) {
		inputs.pop_front();
	}
	yy_pop_state();
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 266 "../src/parser/lexer.lxx"
{
	accept();

	string msg;
	msg += "Treesap doesn't currently support \"#pragma ";
	msg += cpp_yytext;
	msg += "\".";
	yyerror(msg);

	yy_pop_state();
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 278 "../src/parser/lexer.lxx"
{
	// Reads a quoted (") include (& following junk)
	accept();
	if(!accept_include('"')) { yyterminate(); }
	else { yy_pop_state(); }
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 284 "../src/parser/lexer.lxx"
{
	// Reads a braced (<>) include (& following junk)
	accept();
	if(!accept_include('>')) { yyterminate(); }
	else { yy_pop_state(); }
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 291 "../src/parser/lexer.lxx"
{
	// Accepts any character except spaces, <, or "
	accept();

	string msg;
	msg += "Found unexpected \"";
	msg += cpp_yytext;
	msg += "\" in #include directive.";
	yyerror(msg);

	yy_pop_state();
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 304 "../src/parser/lexer.lxx"
{
	accept();
	yy_pop_state();

	inputs.front()->condition_depth++;
	if(macros.find(cpp_yytext) == macros.end()) {
		yy_push_state(elseif);
	} else {
		yy_push_state(INITIAL);
	}

	// Consume the rest of the line, except the newline (\n) character
	int c = peek_char();
	while(c!= '\n' && c != EOF) {
		read_char();
		c = peek_char();
	}
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 323 "../src/parser/lexer.lxx"
{
	accept();
	yy_pop_state();

	string msg;
	msg += "Found unexpected \"";
	msg += cpp_yytext;
	msg += "\" after #ifdef directive.";
	yyerror(msg);

	yy_push_state(endif);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 336 "../src/parser/lexer.lxx"
{
	accept();
	yy_pop_state();

	inputs.front()->condition_depth++;
	if(macros.find(cpp_yytext) == macros.end()) {
		yy_push_state(INITIAL);
	} else {
		yy_push_state(elseif);
	}

	// Consume the rest of the line, except the newline (\n) character
	int c = peek_char();
	while(c!= '\n' && c != EOF) {
		read_char();
		c = peek_char();
	}
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 355 "../src/parser/lexer.lxx"
{
	accept();
	yy_pop_state();

	string msg;
	msg += "Found unexpected \"";
	msg += cpp_yytext;
	msg += "\" in #ifndef directive.";
	yyerror(msg);

	yy_push_state(endif);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 368 "../src/parser/lexer.lxx"
{
	accept();
	scan_define(cpp_yytext);
	yy_pop_state();
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 374 "../src/parser/lexer.lxx"
{
	accept();
	macros.erase(cpp_yytext);

	// Consume the rest of the line, except the newline (\n) character
	int c = peek_char();
	while(c!= '\n' && c != EOF) {
		read_char();
		c = peek_char();
	}

	yy_pop_state();
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 388 "../src/parser/lexer.lxx"
{
	accept();

	string msg;
	msg += "Found unexpected \"";
	msg += cpp_yytext;
	msg += "\" in #undef directive.";
	yyerror(msg);

	// Consume the rest of the line, except the newline (\n) character
	int c = peek_char();
	while(c!= '\n' && c != EOF) {
		read_char();
		c = peek_char();
	}

	yy_pop_state();
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 407 "../src/parser/lexer.lxx"
{
	// If we find (if|ifdef|ifndef), increment our depth by 1 and find #end
	accept();
	inputs.front()->condition_depth++;
	yy_push_state(endif);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 414 "../src/parser/lexer.lxx"
{
	// If we find #else while looking for #else, tokenize the else code
	yy_pop_state();
	yy_push_state(INITIAL);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 420 "../src/parser/lexer.lxx"
{
	// If we find #elif while looking for #else, test the #if
	accept();

	string condition = scan_if();
	if(parse_if_directive(current_module, condition)) {
		yy_pop_state();
		yy_push_state(INITIAL);
	}
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 431 "../src/parser/lexer.lxx"
{
	accept();

	if(inputs.front()->condition_depth == 0) {
		yyerror("Found #endif with no matching #if/#ifdef/#ifndef.");
	} else {
		inputs.front()->condition_depth--;
	}
	yy_pop_state();

}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 443 "../src/parser/lexer.lxx"
{
	// If we find (if|ifdef|ifndef), increment our depth by 1
	accept();
	inputs.front()->condition_depth++;
	yy_push_state(endif);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 450 "../src/parser/lexer.lxx"
{
	// Consume any else
	accept();
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 455 "../src/parser/lexer.lxx"
{
	// Consume any elif
	accept();
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 460 "../src/parser/lexer.lxx"
{
	accept();
	if(inputs.front()->condition_depth == 0) {
		yyerror("Found #endif with no matching #if/#ifdef/#ifndef.");
	} else {
		inputs.front()->condition_depth--;
	}
	yy_pop_state();
}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 470 "../src/parser/lexer.lxx"
{
	accept();

	// Increment the line count
	inputs.front()->current_line = cpp_yytext+1;
	inputs.front()->line_number++;
	inputs.front()->col_number = 0;

	yyless(1);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 481 "../src/parser/lexer.lxx"
{
	accept();
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 485 "../src/parser/lexer.lxx"
{
	accept();
	yywarning(cpp_yytext);
	yy_pop_state();
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 491 "../src/parser/lexer.lxx"
{
	accept();
	yyerror("Treesap failed to handled characters following pre-processor directive.");
	yyterminate();
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 497 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_NAMESPACE);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 502 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_PUBLIC);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 507 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_PRIVATE);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 512 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_PRIVATE);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 517 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_ENUM);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 522 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_CLASS);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 527 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_STRUCT);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 532 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_TYPEDEF);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 537 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_INT);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 542 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_KW_UNSIGNED);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 547 "../src/parser/lexer.lxx"
{
	// Scoping operator
	accept();
	emit(TOKEN_OP_CONS);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 553 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_OP_AND);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 558 "../src/parser/lexer.lxx"
{
	accept();
	emit(TOKEN_OP_STAR);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 563 "../src/parser/lexer.lxx"
{
	// Comment block
	accept();
	inputs.front()->comments.back() += scan_block_comment();
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 569 "../src/parser/lexer.lxx"
{
	// C++-style comment
	accept();
	inputs.front()->comments.back() += (cpp_yytext + 2);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 575 "../src/parser/lexer.lxx"
{
	// String literal (")
	accept();
	yylval.string = new string(scan_string_literal());
	emit(TOKEN_STRING);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 582 "../src/parser/lexer.lxx"
{
	// Character literal (')
	accept();
	yylval.character = read_char_const();
	if(peek_char() != '\'') {
		yyerror("Treesap doesn't support multi-character character constants.");
		scan_string_literal('\''); // Consome the rest of the characters
	}
	emit(TOKEN_CHAR);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 593 "../src/parser/lexer.lxx"
{
	// Boolean literal
	accept();
	if(strcmp(cpp_yytext, "true") == 0) {
		yylval.boolean = true;
	} else {
		yylval.boolean = false;
	}
	emit(TOKEN_BOOLEAN);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 604 "../src/parser/lexer.lxx"
{
	// Octal literal (currently we just accept 0)
	accept();
	yylval.integer = 0;
	emit(TOKEN_INTEGER);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 611 "../src/parser/lexer.lxx"
{
	// Decimal literal
	accept();
	yylval.integer = atoi(cpp_yytext);
	emit(TOKEN_INTEGER);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 618 "../src/parser/lexer.lxx"
{
	// Floating-point literals
	accept();
	yylval.floating = atof(cpp_yytext);
	emit(TOKEN_FLOAT);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 625 "../src/parser/lexer.lxx"
{
	accept();
	yylval.string = new string(cpp_yytext);
	emit(TOKEN_IDENTIFIER);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 631 "../src/parser/lexer.lxx"
{
	// Send any other printable character as itself.
	accept();
	emit(cpp_yytext[0]);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(pragma):
case YY_STATE_EOF(include):
case YY_STATE_EOF(ifdef):
case YY_STATE_EOF(ifndef):
case YY_STATE_EOF(define):
case YY_STATE_EOF(undef):
case YY_STATE_EOF(elseif):
case YY_STATE_EOF(endif):
case YY_STATE_EOF(warning):
#line 637 "../src/parser/lexer.lxx"
{
	// Check for unclosed conditionals
	while(inputs.front()->condition_depth > 0) {
		yyerror("Missing #endif in current file.");
		inputs.front()->condition_depth--;
	}

	// Stop reading our current file
	cpp_yypop_buffer_state();
	inputs.pop_front();

	// Check if we have a file to return to (for example, after an #include)
	if(!YY_CURRENT_BUFFER) {
		// Check if we have inputs left in our queue
		if(inputs.empty()) {
			yyterminate();
		}

		cpp_yyin = fopen(inputs.front()->name.c_str(), "r");
		if(!cpp_yyin) {
			yyerror("Could not open file \"" + inputs.front()->name + "\" for scanning.");
			yyterminate();
		}

		cpp_yypush_buffer_state(yy_new_buffer(cpp_yyin, YY_BUF_SIZE));
	}
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 665 "../src/parser/lexer.lxx"
ECHO;
	YY_BREAK
#line 1838 "../src/parser/lexer.cxx"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cpp_yyin at a new source and called
			 * cpp_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cpp_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cpp_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cpp_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cpp_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cpp_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cpp_yyrestart(cpp_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cpp_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 259);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cpp_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cpp_yyrestart(cpp_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cpp_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cpp_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cpp_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cpp_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cpp_yy_create_buffer(cpp_yyin,YY_BUF_SIZE );
	}

	cpp_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	cpp_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cpp_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cpp_yypop_buffer_state();
	 *		cpp_yypush_buffer_state(new_buffer);
     */
	cpp_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cpp_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cpp_yywrap()) processing, but the only time this flag
	 * is looked at is after cpp_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cpp_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cpp_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cpp_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cpp_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cpp_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cpp_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cpp_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cpp_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cpp_yy_create_buffer()
 * 
 */
    void cpp_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cpp_yyfree((void *) b->yy_ch_buf  );

	cpp_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cpp_yyrestart() or at EOF.
 */
    static void cpp_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cpp_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cpp_yy_init_buffer was _probably_
     * called from cpp_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cpp_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cpp_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cpp_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cpp_yyensure_buffer_stack();

	/* This block is copied from cpp_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cpp_yy_switch_to_buffer. */
	cpp_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cpp_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cpp_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cpp_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cpp_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cpp_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cpp_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cpp_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cpp_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cpp_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cpp_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cpp_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cpp_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cpp_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cpp_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE cpp_yy_scan_string (yyconst char * yystr )
{
    
	return cpp_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cpp_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cpp_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cpp_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cpp_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cpp_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cpp_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) cpp_yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) cpp_yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cpp_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cpp_yytext[cpp_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = cpp_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cpp_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cpp_yyget_lineno  (void)
{
        
    return cpp_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *cpp_yyget_in  (void)
{
        return cpp_yyin;
}

/** Get the output stream.
 * 
 */
FILE *cpp_yyget_out  (void)
{
        return cpp_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t cpp_yyget_leng  (void)
{
        return cpp_yyleng;
}

/** Get the current token.
 * 
 */

char *cpp_yyget_text  (void)
{
        return cpp_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cpp_yyset_lineno (int  line_number )
{
    
    cpp_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cpp_yy_switch_to_buffer
 */
void cpp_yyset_in (FILE *  in_str )
{
        cpp_yyin = in_str ;
}

void cpp_yyset_out (FILE *  out_str )
{
        cpp_yyout = out_str ;
}

int cpp_yyget_debug  (void)
{
        return cpp_yy_flex_debug;
}

void cpp_yyset_debug (int  bdebug )
{
        cpp_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cpp_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    cpp_yyin = stdin;
    cpp_yyout = stdout;
#else
    cpp_yyin = (FILE *) 0;
    cpp_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cpp_yylex_init()
     */
    return 0;
}

/* cpp_yylex_destroy is for both reentrant and non-reentrant scanners. */
int cpp_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cpp_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cpp_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	cpp_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        cpp_yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cpp_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cpp_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cpp_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cpp_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see cpp_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 665 "../src/parser/lexer.lxx"



// accept is called above as each piece is pulled off and
// accepted by the lexer; it increments the current column number.
static void accept() {
	yylloc.file = inputs.front();
	yylloc.first_line = inputs.front()->line_number;
	yylloc.first_column = inputs.front()->col_number;
	inputs.front()->col_number += cpp_yyleng;
}

// peek_char returns the character that will be returned by read_char next.
inline int peek_char()
{
	int c = yyinput();
	unput(c);
	return c;
}

// read_char reads and returns a single character,
//     incrementing the line and column numbers as appropriate.
inline int read_char() {
	return read_char(inputs.front()->line_number, inputs.front()->col_number);
}
static int read_char(int & line, int & col) {
	int c = yyinput();
	if (c == '\n') {
		line++;
		col = 0;
	} else {
		col++;
	}
	return c;
}

inline char read_char_const(bool auto_escape) {
	return read_char_const(inputs.front()->line_number, inputs.front()->col_number, auto_escape);
}
static char read_char_const(int & line, int & col, bool auto_escape) {
	int c;

	if(!auto_escape) { c = '\\'; }
	else { c = read_char(line, col); }

	if(c != '\\') { return c; }

	// Handle escape sequence
	c = read_char(line, col);
	switch(c) {
		case 'a':
			return '\a';
		case 'b':
			return '\b';
		case 'f':
			return '\f';
		case 'n':
			return '\n';
		case 'r':
			return '\r';
		case 't':
			return '\t';
		case 'v':
			return '\v';
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		{
			int oct = (c - '0'); // integer value

			c = peek_char();
			if(c < '0' || c > '7') { return oct; }
			for(int i = 0; i < 2; ++i) {
				read_char(line, col);
				oct = oct * 8 + (c - '0');

				c = peek_char();
				if(c < '0' || c > '7') { return oct; }
			}
			if(oct > 255) {
				yyerror("Octal escape sequence out of range.");
			}
			return (char)oct;
		}
		case 'x':
		{
			int hex = 0;

			c = peek_char();
			if(!isxdigit(c)) { return hex; }
			for(int i = 0; i < 2; i++) {
				read_char(line, col);
				hex = hex * 16 + (isdigit(c) ? (c - '0') : tolower(c) - 'a' + 10);

				c = peek_char();
				if(!isxdigit(c)) { return hex; }
			}
			return (char)hex;
		}
		case 'u':
			yyerror("Treesap hasn't implement unicode escape sequences yet!");
			return 'u';
		default:
			return c;
	}
}

static void eat_space() {
	int c = peek_char();
	while(isblank(c)) {
		read_char();
		c = peek_char();
	}
}

static void scan_define(const string& identifier) {
	Macro def;
	def.identifier = identifier;
	def.location = Location(inputs.front());

	int c = peek_char();
	if(c == '(') {
		read_char();
		def.is_function = true;

		// Read function macro
		string arg;
		c = read_char();
		while(c != EOF && c != ')') {
			if(c == ',') {
				if(arg.empty()) {
					yywarning("Found extra ',' character in macro definition.");
				}

				def.args.push_back(arg);
				arg = "";
			} else if(c == '\n') {
				yyerror("Found newline in function macro definition.");
				unput(c);
				return;
			} else if(isalnum(c) || c == '_') {
				arg += c;
			} else if(!isblank(c)) {
				string msg;
				msg += "Found unexpeced character '";
				msg += c;
				msg += "' in argument for macro definition.";
				yyerror(msg);
			}
			c = read_char();
		}

		if(c == EOF) {
			yyerror("Unexpected EOF in function macro definition.");
			unput(c);
			return;
		}
	}

	eat_space();

	// Read value for macro
	string replace;
	c = peek_char();
	while(c != EOF && c != '\n') {
		read_char();
		int p = peek_char();
		if(c == '\\' && p == '\n') {
			replace += read_char();
		} else {
			replace += c;
		}

		c = peek_char();
	}

	def.replace_text = replace;
	macros.emplace(identifier, def);
}

static string scan_if() {
	string result;
	int c = read_char();
	while(c != EOF && c != '\n') {
		if(c == '\\' && peek_char() == '\n') {
			c = read_char();
		}

		result += c;
		c = read_char();
	}

	return result;
}

static string scan_block_comment() {
	// We don't touch the current line number and column number during
	// scanning, so that if we detect a warning while scanning the comment
	// (e.g. an unterminated block comment), we'll report the warning as
	// occurring at the start of the comment, not at the end--somewhat
	// more convenient for the user.
	string result;
	int line = inputs.front()->line_number;
	int col = inputs.front()->col_number;

	int c = read_char(line, col);
	while(c != EOF) {
		if(c == '*' && peek_char() == '/') { break; }
		c = read_char(line, col);
	}

	if(c == EOF) {
		yyerror("Block comment is missing a terminating \"*/\"."); 
	} else {
		read_char(line, col); // consume '/' following the '*'
	}

	inputs.front()->line_number = line;
	inputs.front()->col_number = line;

	return result;
}

static string scan_string_literal(char quote_mark) {
	// We don't touch the current line number and column number during
	// scanning, so that if we detect an error while scanning the string
	// (e.g. an unterminated string), we'll report the error as
	// occurring at the start of the string, not at the end--somewhat
	// more convenient for the user.
	string result;
	int line = inputs.front()->line_number;
	int col = inputs.front()->col_number;

	int c = read_char(line, col);
	while(c != quote_mark && c != EOF) {
		// A newline is not allowed within a string unless it is escaped.
		if(c == '\n') {
			c = EOF;
			break;
		}

		if(c == '\\') {
			result += read_char_const(line, col, true);
		} else {
			result += c;
		}

		c = read_char(line, col);
	}

	if(c == EOF)
	{
		yyerror("String const is missing a terminating (\") character."); 
	}

	inputs.front()->line_number = line;
	inputs.front()->col_number = line;

	return result;
}

static bool accept_include(char end_mark) {
	// Get the string between the quotes
	string filename;
	int line = inputs.front()->line_number;
	int col = inputs.front()->col_number;

	int c = read_char(line, col);
	while(c != end_mark && c != EOF) {
		filename += c;
		c = read_char(line, col);
	}

	if(c == EOF) {
		string msg = "#include filename missing a terminating (";
		yyerror(msg + "\" character.");
		return false;
	}

	if(filename.empty()) {
		yyerror("#include must be given a filename.");
		return false;
	}

	string fileref;
	vector<string> dirs;

	if(end_mark == '\"') {
		cpp_yyin = fopen(filename.c_str(), "r");
		if(cpp_yyin) {
			fileref = filename;
			goto eatline;
		}
	}

	dirs = get_compiler_includes();
	for(auto it = dirs.begin(); it != dirs.end(); ++it) {
		string filepath = (*it) + filename;
		cpp_yyin = fopen(filepath.c_str(), "r");
		if(cpp_yyin) {
			fileref = filepath;
			goto eatline;
		}
	}

	if(!cpp_yyin) {
		yyerror("Could not open file " + filename + " for scanning.");
		return false;
	}

  eatline:
	inputs.front()->line_number = line;
	inputs.front()->col_number = col;

	c = peek_char();
	while(c != EOF && c != '\n') {
		read_char();
		switch(c) {
			case ' ':
			case '\t':
				// Eat any whitespace
				break;
			case '/':
				// Ignore comments
				goto stop;
			default:
				yywarning("Junk characters after #include.");
				goto stop;
		}
		c = peek_char();
	}

  stop:
  	auto prev_include = files.find(fileref);
  	if(prev_include != files.end()) {
  		if(prev_include->second->type != FTInput) {
  			yyerror("Name conflict with included file.");
  			return false;
  		}

  		Input* input = (Input*)(prev_include->second);
  		inputs.push_front(input);
  		input->times_included++;
  	} else {
  		Input* input = new Input(fileref);
		inputs.push_front(input);
		files.emplace(input->name, input);  		
  	}

	// Switch to the new buffer
	cpp_yypush_buffer_state(yy_new_buffer(cpp_yyin, YY_BUF_SIZE));
	return true;
}

static ostream& indent(ostream& out, unsigned int indent_level) {
	for(unsigned int i = 0; i < indent_level; i++) {
		out << ' ';
	}
	return out;
}

Module* init_lexer(const string & filename) {
	error_count = 0;
	warning_count = 0;

	current_module = new Module();

	macros.clear();
	vector<Macro> predefines = get_compiler_defines();
	for(auto it = predefines.begin(); it != predefines.end(); ++it) {
		macros.emplace(it->identifier, (*it));
	}

	inputs.clear();
	Input* input = new Input(filename);
	inputs.push_front(input);
	files.emplace(filename, input);

	cpp_yyout = fopen("/dev/null", "w");
	cpp_yyin = fopen(filename.c_str(), "r");
	if(!cpp_yyin) { return NULL; }
	return current_module;
}

int cpp_yyerrors() { return error_count; }
int cpp_yywarnings() { return warning_count; }
void cpp_yyerror(const string & msg)
{
	Input* info = inputs.front();

	cerr << "Error";
	if(!info->name.empty()) {
		cerr << " in " << info->name;
	}
	cerr << " at line " << info->line_number << ", column " << info->col_number
	     << ":\n" << info->current_line << "\n";

	int ident = info->col_number - 1 < 0 ? 0 : info->col_number - 1;
	if(ident > 10) { ident = 10; }
	indent(cerr, ident) << "^\n";
	cerr << msg << "\n\n";

	error_count++;
}
void cpp_yywarning(const string & msg)
{
	Input* info = inputs.front();

	cerr << "\nWarning";
	if(!info->name.empty()) {
		cerr << " in " << info->name;
	}
	cerr << " at line " << info->line_number << ", column " << info->col_number
	     << ":\n" << info->current_line << "\n";

	int ident = info->col_number - 1 < 0 ? 0 : info->col_number - 1;
	if(ident > 10) { ident = 10; }
	indent(cerr, ident) << "^\n";
	cerr << msg << "\n\n";

	warning_count++;
}

Input::Input(const string& name) : File(name, FTInput), line_number(1), col_number(0), times_included(1) {
	comments.push_back(string());
}

