(function(e,a){e.version="0.9.2";e.protocol=1;e.transports=[];e.j=[];e.sockets={};e.connect=function(b,c){var g=e.util.parseUri(b),f,d;a&&a.location&&(g.protocol=g.protocol||a.location.protocol.slice(0,-1),g.host=g.host||(a.document?a.document.domain:a.location.hostname),g.port=g.port||a.location.port);f=e.util.uniqueUri(g);var l={host:g.host,secure:"https"==g.protocol,port:g.port||("https"==g.protocol?443:80),query:g.query||""};e.util.merge(l,c);if(l["force new connection"]||!e.sockets[f])d=new e.Socket(l);
!l["force new connection"]&&d&&(e.sockets[f]=d);d=d||e.sockets[f];return d.of(1<g.path.length?g.path:"")}})("object"===typeof module?module.exports:this.io={},this);
(function(e,a){var b=e.util={},c=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,g="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");b.parseUri=function(d){d=c.exec(d||"");for(var a={},b=14;b--;)a[g[b]]=d[b]||"";return a};b.uniqueUri=function(d){var c=d.protocol,b=d.host;d=d.port;"document"in
a?(b=b||document.domain,d=d||("https"==c&&"https:"!==document.location.protocol?443:document.location.port)):(b=b||"localhost",!d&&"https"==c&&(d=443));return(c||"http")+"://"+b+":"+(d||80)};b.query=function(d,a){var c=b.chunkQuery(d||""),f=[];b.merge(c,b.chunkQuery(a||""));for(var g in c)c.hasOwnProperty(g)&&f.push(g+"="+c[g]);return f.length?"?"+f.join("&"):""};b.chunkQuery=function(d){var a={};d=d.split("&");for(var c=0,b=d.length,f;c<b;++c)f=d[c].split("="),f[0]&&(a[f[0]]=f[1]);return a};var f=
!1;b.load=function(d){if("document"in a&&"complete"===document.readyState||f)return d();b.on(a,"load",d,!1)};b.on=function(d,a,c,b){d.attachEvent?d.attachEvent("on"+a,c):d.addEventListener&&d.addEventListener(a,c,b)};b.request=function(d){if(d&&"undefined"!=typeof XDomainRequest)return new XDomainRequest;if("undefined"!=typeof XMLHttpRequest&&(!d||b.ua.hasCORS))return new XMLHttpRequest;if(!d)try{return new (window[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(a){}return null};
"undefined"!=typeof window&&b.load(function(){f=!0});b.defer=function(d){if(!b.ua.webkit||"undefined"!=typeof importScripts)return d();b.load(function(){setTimeout(d,100)})};b.merge=function(d,a,c,f){f=f||[];c="undefined"==typeof c?2:c;for(var g in a)a.hasOwnProperty(g)&&0>b.indexOf(f,g)&&("object"!==typeof d[g]||!c?(d[g]=a[g],f.push(a[g])):b.merge(d[g],a[g],c-1,f));return d};b.mixin=function(a,c){b.merge(a.prototype,c.prototype)};b.inherit=function(a,c){function b(){}b.prototype=c.prototype;a.prototype=
new b};b.isArray=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};b.intersect=function(a,c){for(var f=[],g=a.length>c.length?a:c,e=a.length>c.length?c:a,n=0,u=e.length;n<u;n++)~b.indexOf(g,e[n])&&f.push(e[n]);return f};b.indexOf=function(a,c,b){var f=a.length;for(b=0>b?0>b+f?0:b+f:b||0;b<f&&a[b]!==c;b++);return f<=b?-1:b};b.toArray=function(a){for(var c=[],b=0,f=a.length;b<f;b++)c.push(a[b]);return c};b.ua={};b.ua.hasCORS="undefined"!=typeof XMLHttpRequest&&function(){try{var a=
new XMLHttpRequest}catch(c){return!1}return void 0!=a.withCredentials}();b.ua.webkit="undefined"!=typeof navigator&&/webkit/i.test(navigator.userAgent)})("undefined"!=typeof io?io:module.exports,this);
(function(e,a){function b(){}e.EventEmitter=b;b.prototype.on=function(c,b){this.$events||(this.$events={});this.$events[c]?a.util.isArray(this.$events[c])?this.$events[c].push(b):this.$events[c]=[this.$events[c],b]:this.$events[c]=b;return this};b.prototype.addListener=b.prototype.on;b.prototype.once=function(a,b){function f(){d.removeListener(a,f);b.apply(this,arguments)}var d=this;f.listener=b;this.on(a,f);return this};b.prototype.removeListener=function(c,b){if(this.$events&&this.$events[c]){var f=
this.$events[c];if(a.util.isArray(f)){for(var d=-1,l=0,m=f.length;l<m;l++)if(f[l]===b||f[l].listener&&f[l].listener===b){d=l;break}if(0>d)return this;f.splice(d,1);f.length||delete this.$events[c]}else(f===b||f.listener&&f.listener===b)&&delete this.$events[c]}return this};b.prototype.removeAllListeners=function(a){this.$events&&this.$events[a]&&(this.$events[a]=null);return this};b.prototype.listeners=function(b){this.$events||(this.$events={});this.$events[b]||(this.$events[b]=[]);a.util.isArray(this.$events[b])||
(this.$events[b]=[this.$events[b]]);return this.$events[b]};b.prototype.emit=function(b){if(!this.$events)return!1;var g=this.$events[b];if(!g)return!1;var f=Array.prototype.slice.call(arguments,1);if("function"==typeof g)g.apply(this,f);else if(a.util.isArray(g))for(var g=g.slice(),d=0,l=g.length;d<l;d++)g[d].apply(this,f);else return!1;return!0}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(e,a){function b(a){return 10>a?"0"+a:a}function c(a){l.lastIndex=0;return l.test(a)?'"'+a.replace(l,function(a){var b=p[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function g(a,d){var f,l,e,p,q=m,t,r=d[a];r instanceof Date&&(r=isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null);"function"===typeof n&&(r=n.call(d,a,
r));switch(typeof r){case "string":return c(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";m+=s;t=[];if("[object Array]"===Object.prototype.toString.apply(r)){p=r.length;for(f=0;f<p;f+=1)t[f]=g(f,r)||"null";e=0===t.length?"[]":m?"[\n"+m+t.join(",\n"+m)+"\n"+q+"]":"["+t.join(",")+"]";m=q;return e}if(n&&"object"===typeof n){p=n.length;for(f=0;f<p;f+=1)"string"===typeof n[f]&&(l=n[f],(e=g(l,r))&&t.push(c(l)+(m?": ":":")+
e))}else for(l in r)Object.prototype.hasOwnProperty.call(r,l)&&(e=g(l,r))&&t.push(c(l)+(m?": ":":")+e);e=0===t.length?"{}":m?"{\n"+m+t.join(",\n"+m)+"\n"+q+"}":"{"+t.join(",")+"}";m=q;return e}}if(a&&a.parse)return e.JSON={parse:a.parse,stringify:a.stringify};var f=e.JSON={},d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
m,s,p={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;f.stringify=function(a,b,c){var d;s=m="";if("number"===typeof c)for(d=0;d<c;d+=1)s+=" ";else"string"===typeof c&&(s=c);if((n=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return g("",{"":a})};f.parse=function(a,b){function c(a,d){var f,l,g=a[d];if(g&&"object"===typeof g)for(f in g)Object.prototype.hasOwnProperty.call(g,f)&&(l=c(g,f),void 0!==l?g[f]=l:
delete g[f]);return b.call(a,d,g)}var f;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),"function"===typeof b?c({"":f},""):f;throw new SyntaxError("JSON.parse");}})("undefined"!=typeof io?io:module.exports,
"undefined"!==typeof JSON?JSON:void 0);
(function(e,a){var b=e.parser={},c=b.packets="disconnect connect heartbeat message json event ack error noop".split(" "),g=b.reasons=["transport not supported","client not handshaken","unauthorized"],f=b.advice=["reconnect"],d=a.JSON,l=a.util.indexOf;b.encodePacket=function(a){var b=l(c,a.type),e=a.id||"",m=a.endpoint||"",v=a.ack,w=null;switch(a.type){case "error":var D=a.reason?l(g,a.reason):"";a=a.advice?l(f,a.advice):"";if(""!==D||""!==a)w=D+(""!==a?"+"+a:"");break;case "message":""!==a.data&&
(w=a.data);break;case "event":w={name:a.name};a.args&&a.args.length&&(w.args=a.args);w=d.stringify(w);break;case "json":w=d.stringify(a.data);break;case "connect":a.qs&&(w=a.qs);break;case "ack":w=a.ackId+(a.args&&a.args.length?"+"+d.stringify(a.args):"")}b=[b,e+("data"==v?"+":""),m];null!==w&&void 0!==w&&b.push(w);return b.join(":")};b.encodePayload=function(a){var b="";if(1==a.length)return a[0];for(var c=0,d=a.length;c<d;c++)b+="\ufffd"+a[c].length+"\ufffd"+a[c];return b};var m=/([^:]+):([0-9]+)?(\+)?:([^:]+)?:?([\s\S]*)?/;
b.decodePacket=function(a){var b=a.match(m);if(!b)return{};var l=b[2]||"";a=b[5]||"";var e={type:c[b[1]],endpoint:b[4]||""};l&&(e.id=l,e.ack=b[3]?"data":!0);switch(e.type){case "error":b=a.split("+");e.reason=g[b[0]]||"";e.advice=f[b[1]]||"";break;case "message":e.data=a||"";break;case "event":try{var v=d.parse(a);e.name=v.name;e.args=v.args}catch(w){}e.args=e.args||[];break;case "json":try{e.data=d.parse(a)}catch(D){}break;case "connect":e.qs=a||"";break;case "ack":if(b=a.match(/^([0-9]+)(\+)?(.*)/))if(e.ackId=
b[1],e.args=[],b[3])try{e.args=b[3]?d.parse(b[3]):[]}catch(z){}}return e};b.decodePayload=function(a){if("\ufffd"==a.charAt(0)){for(var c=[],d=1,f="";d<a.length;d++)"\ufffd"==a.charAt(d)?(c.push(b.decodePacket(a.substr(d+1).substr(0,f))),d+=Number(f)+1,f=""):f+=a.charAt(d);return c}return[b.decodePacket(a)]}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(e,a){function b(a,b){this.socket=a;this.sessid=b}e.Transport=b;a.util.mixin(b,a.EventEmitter);b.prototype.onData=function(b){this.clearCloseTimeout();(this.socket.connected||this.socket.connecting||this.socket.reconnecting)&&this.setCloseTimeout();if(""!==b&&(b=a.parser.decodePayload(b))&&b.length)for(var g=0,f=b.length;g<f;g++)this.onPacket(b[g]);return this};b.prototype.onPacket=function(a){this.socket.setHeartbeatTimeout();if("heartbeat"==a.type)return this.onHeartbeat();if("connect"==
a.type&&""==a.endpoint)this.onConnect();this.socket.onPacket(a);return this};b.prototype.setCloseTimeout=function(){if(!this.closeTimeout){var a=this;this.closeTimeout=setTimeout(function(){a.onDisconnect()},this.socket.closeTimeout)}};b.prototype.onDisconnect=function(){this.close&&this.open&&this.close();this.clearTimeouts();this.socket.onDisconnect();return this};b.prototype.onConnect=function(){this.socket.onConnect();return this};b.prototype.clearCloseTimeout=function(){this.closeTimeout&&(clearTimeout(this.closeTimeout),
this.closeTimeout=null)};b.prototype.clearTimeouts=function(){this.clearCloseTimeout();this.reopenTimeout&&clearTimeout(this.reopenTimeout)};b.prototype.packet=function(b){this.send(a.parser.encodePacket(b))};b.prototype.onHeartbeat=function(a){this.packet({type:"heartbeat"})};b.prototype.onOpen=function(){this.open=!0;this.clearCloseTimeout();this.socket.onOpen()};b.prototype.onClose=function(){this.open=!1;this.socket.onClose();this.onDisconnect()};b.prototype.prepareUrl=function(){var b=this.socket.options;
return this.scheme()+"://"+b.host+":"+b.port+"/"+b.resource+"/"+a.protocol+"/"+this.name+"/"+this.sessid};b.prototype.ready=function(a,b){b.call(this)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(e,a,b){function c(f){this.options={port:80,secure:!1,document:"document"in b?document:!1,resource:"socket.io",transports:a.transports,"connect timeout":1E4,"try multiple transports":!0,reconnect:!0,"reconnection delay":500,"reconnection limit":Infinity,"reopen delay":3E3,"max reconnection attempts":10,"sync disconnect on unload":!0,"auto connect":!0,"flash policy port":10843};a.util.merge(this.options,f);this.reconnecting=this.connecting=this.open=this.connected=!1;this.namespaces={};this.buffer=
[];this.doBuffer=!1;if(this.options["sync disconnect on unload"]&&(!this.isXDomain()||a.util.ua.hasCORS)){var d=this;a.util.on(b,"beforeunload",function(){d.disconnectSync()},!1)}this.options["auto connect"]&&this.connect()}function g(){}e.Socket=c;a.util.mixin(c,a.EventEmitter);c.prototype.of=function(b){this.namespaces[b]||(this.namespaces[b]=new a.SocketNamespace(this,b),""!==b&&this.namespaces[b].packet({type:"connect"}));return this.namespaces[b]};c.prototype.publish=function(){this.emit.apply(this,
arguments);var a,b;for(b in this.namespaces)this.namespaces.hasOwnProperty(b)&&(a=this.of(b),a.$emit.apply(a,arguments))};c.prototype.handshake=function(b){function d(a){if(a instanceof Error)c.onError(a.message);else b.apply(null,a.split(":"))}var c=this,e=this.options,e=["http"+(e.secure?"s":"")+":/",e.host+":"+e.port,e.resource,a.protocol,a.util.query(this.options.query,"t="+ +new Date)].join("/");if(this.isXDomain()&&!a.util.ua.hasCORS){var s=document.getElementsByTagName("script")[0],p=document.createElement("script");
p.src=e+"&jsonp="+a.j.length;s.parentNode.insertBefore(p,s);a.j.push(function(a){d(a);p.parentNode.removeChild(p)})}else{var n=a.util.request();n.open("GET",e,!0);n.withCredentials=!0;n.onreadystatechange=function(){4==n.readyState&&(n.onreadystatechange=g,200==n.status?d(n.responseText):!c.reconnecting&&c.onError(n.responseText))};n.send(null)}};c.prototype.getTransport=function(b){b=b||this.transports;for(var d=0,c;c=b[d];d++)if(a.Transport[c]&&a.Transport[c].check(this)&&(!this.isXDomain()||a.Transport[c].xdomainCheck()))return new a.Transport[c](this,
this.sessionid);return null};c.prototype.connect=function(b){if(this.connecting)return this;var d=this;this.handshake(function(c,g,e,p){function n(a){d.transport&&d.transport.clearTimeouts();d.transport=d.getTransport(a);if(!d.transport)return d.publish("connect_failed");d.transport.ready(d,function(){d.connecting=!0;d.publish("connecting",d.transport.name);d.transport.open();d.options["connect timeout"]&&(d.connectTimeoutTimer=setTimeout(function(){if(!d.connected&&(d.connecting=!1,d.options["try multiple transports"])){d.remainingTransports||
(d.remainingTransports=d.transports.slice(0));for(var a=d.remainingTransports;0<a.length&&a.splice(0,1)[0]!=d.transport.name;);a.length?n(a):d.publish("connect_failed")}},d.options["connect timeout"]))})}d.sessionid=c;d.closeTimeout=1E3*e;d.heartbeatTimeout=1E3*g;d.transports=a.util.intersect(p.split(","),d.options.transports);d.setHeartbeatTimeout();n(d.options.transports);d.once("connect",function(){clearTimeout(d.connectTimeoutTimer);b&&"function"==typeof b&&b()})});return this};c.prototype.setHeartbeatTimeout=
function(){clearTimeout(this.heartbeatTimeoutTimer);var a=this;this.heartbeatTimeoutTimer=setTimeout(function(){a.transport.onClose()},this.heartbeatTimeout)};c.prototype.packet=function(a){this.connected&&!this.doBuffer?this.transport.packet(a):this.buffer.push(a);return this};c.prototype.setBuffer=function(a){this.doBuffer=a;!a&&(this.connected&&this.buffer.length)&&(this.transport.payload(this.buffer),this.buffer=[])};c.prototype.disconnect=function(){if(this.connected||this.connecting)this.open&&
this.of("").packet({type:"disconnect"}),this.onDisconnect("booted");return this};c.prototype.disconnectSync=function(){a.util.request().open("GET",this.resource+"/"+a.protocol+"/"+this.sessionid,!0);this.onDisconnect("booted")};c.prototype.isXDomain=function(){var a=b.location.port||("https:"==b.location.protocol?443:80);return this.options.host!==b.location.hostname||this.options.port!=a};c.prototype.onConnect=function(){this.connected||(this.connected=!0,this.connecting=!1,this.doBuffer||this.setBuffer(!1),
this.emit("connect"))};c.prototype.onOpen=function(){this.open=!0};c.prototype.onClose=function(){this.open=!1;clearTimeout(this.heartbeatTimeoutTimer)};c.prototype.onPacket=function(a){this.of(a.endpoint).onPacket(a)};c.prototype.onError=function(a){if(a&&a.advice&&"reconnect"===a.advice&&(this.connected||this.connecting))this.disconnect(),this.options.reconnect&&this.reconnect();this.publish("error",a&&a.reason?a.reason:a)};c.prototype.onDisconnect=function(a){var b=this.connected,c=this.connecting;
this.open=this.connecting=this.connected=!1;if(b||c)this.transport.close(),this.transport.clearTimeouts(),b&&(this.publish("disconnect",a),"booted"!=a&&(this.options.reconnect&&!this.reconnecting)&&this.reconnect())};c.prototype.reconnect=function(){function a(){if(c.connected){for(var f in c.namespaces)c.namespaces.hasOwnProperty(f)&&""!==f&&c.namespaces[f].packet({type:"connect"});c.publish("reconnect",c.transport.name,c.reconnectionAttempts)}clearTimeout(c.reconnectionTimer);c.removeListener("connect_failed",
b);c.removeListener("connect",b);c.reconnecting=!1;delete c.reconnectionAttempts;delete c.reconnectionDelay;delete c.reconnectionTimer;delete c.redoTransports;c.options["try multiple transports"]=e}function b(){if(c.reconnecting){if(c.connected)return a();if(c.connecting&&c.reconnecting)return c.reconnectionTimer=setTimeout(b,1E3);c.reconnectionAttempts++>=g?c.redoTransports?(c.publish("reconnect_failed"),a()):(c.on("connect_failed",b),c.options["try multiple transports"]=!0,c.transport=c.getTransport(),
c.redoTransports=!0,c.connect()):(c.reconnectionDelay<p&&(c.reconnectionDelay*=2),c.connect(),c.publish("reconnecting",c.reconnectionDelay,c.reconnectionAttempts),c.reconnectionTimer=setTimeout(b,c.reconnectionDelay))}}this.reconnecting=!0;this.reconnectionAttempts=0;this.reconnectionDelay=this.options["reconnection delay"];var c=this,g=this.options["max reconnection attempts"],e=this.options["try multiple transports"],p=this.options["reconnection limit"];this.options["try multiple transports"]=!1;
this.reconnectionTimer=setTimeout(b,this.reconnectionDelay);this.on("connect",b)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(e,a){function b(a,b){this.socket=a;this.name=b||"";this.flags={};this.json=new c(this,"json");this.ackPackets=0;this.acks={}}function c(a,b){this.namespace=a;this.name=b}e.SocketNamespace=b;a.util.mixin(b,a.EventEmitter);b.prototype.$emit=a.EventEmitter.prototype.emit;b.prototype.of=function(){return this.socket.of.apply(this.socket,arguments)};b.prototype.packet=function(a){a.endpoint=this.name;this.socket.packet(a);this.flags={};return this};b.prototype.send=function(a,b){var c={type:this.flags.json?
"json":"message",data:a};"function"==typeof b&&(c.id=++this.ackPackets,c.ack=!0,this.acks[c.id]=b);return this.packet(c)};b.prototype.emit=function(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1],e={type:"event",name:a};"function"==typeof c&&(e.id=++this.ackPackets,e.ack="data",this.acks[e.id]=c,b=b.slice(0,b.length-1));e.args=b;return this.packet(e)};b.prototype.disconnect=function(){""===this.name?this.socket.disconnect():(this.packet({type:"disconnect"}),this.$emit("disconnect"));
return this};b.prototype.onPacket=function(b){function c(){d.packet({type:"ack",args:a.util.toArray(arguments),ackId:b.id})}var d=this;switch(b.type){case "connect":this.$emit("connect");break;case "disconnect":if(""===this.name)this.socket.onDisconnect(b.reason||"booted");else this.$emit("disconnect",b.reason);break;case "message":case "json":var e=["message",b.data];"data"==b.ack?e.push(c):b.ack&&this.packet({type:"ack",ackId:b.id});this.$emit.apply(this,e);break;case "event":e=[b.name].concat(b.args);
"data"==b.ack&&e.push(c);this.$emit.apply(this,e);break;case "ack":this.acks[b.ackId]&&(this.acks[b.ackId].apply(this,b.args),delete this.acks[b.ackId]);break;case "error":if(b.advice)this.socket.onError(b);else"unauthorized"==b.reason?this.$emit("connect_failed",b.reason):this.$emit("error",b.reason)}};c.prototype.send=function(){this.namespace.flags[this.name]=!0;this.namespace.send.apply(this.namespace,arguments)};c.prototype.emit=function(){this.namespace.flags[this.name]=!0;this.namespace.emit.apply(this.namespace,
arguments)}})("undefined"!=typeof io?io:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(e,a,b){function c(b){a.Transport.apply(this,arguments)}e.websocket=c;a.util.inherit(c,a.Transport);c.prototype.name="websocket";c.prototype.open=function(){var c=a.util.query(this.socket.options.query),f=this,d;d||(d=b.MozWebSocket||b.WebSocket);this.websocket=new d(this.prepareUrl()+c);this.websocket.onopen=function(){f.onOpen();f.socket.setBuffer(!1)};this.websocket.onmessage=function(a){f.onData(a.data)};this.websocket.onclose=function(){f.onClose();f.socket.setBuffer(!0)};this.websocket.onerror=
function(a){f.onError(a)};return this};c.prototype.send=function(a){this.websocket.send(a);return this};c.prototype.payload=function(a){for(var b=0,c=a.length;b<c;b++)this.packet(a[b]);return this};c.prototype.close=function(){this.websocket.close();return this};c.prototype.onError=function(a){this.socket.onError(a)};c.prototype.scheme=function(){return this.socket.options.secure?"wss":"ws"};c.check=function(){return"WebSocket"in b&&!("__addTask"in WebSocket)||"MozWebSocket"in b};c.xdomainCheck=function(){return!0};
a.transports.push("websocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(e,a){function b(){a.Transport.websocket.apply(this,arguments)}e.flashsocket=b;a.util.inherit(b,a.Transport.websocket);b.prototype.name="flashsocket";b.prototype.open=function(){var b=this,e=arguments;WebSocket.__addTask(function(){a.Transport.websocket.prototype.open.apply(b,e)});return this};b.prototype.send=function(){var b=this,e=arguments;WebSocket.__addTask(function(){a.Transport.websocket.prototype.send.apply(b,e)});return this};b.prototype.close=function(){WebSocket.__tasks.length=
0;a.Transport.websocket.prototype.close.call(this);return this};b.prototype.ready=function(c,e){function f(){var a=c.options,f=a["flash policy port"],s=["http"+(a.secure?"s":"")+":/",a.host+":"+a.port,a.resource,"static/flashsocket","WebSocketMain"+(c.isXDomain()?"Insecure":"")+".swf"];b.loaded||("undefined"===typeof WEB_SOCKET_SWF_LOCATION&&(WEB_SOCKET_SWF_LOCATION=s.join("/")),843!==f&&WebSocket.loadFlashPolicyFile("xmlsocket://"+a.host+":"+f),WebSocket.__initialize(),b.loaded=!0);e.call(d)}var d=
this;if(document.body)return f();a.util.load(f)};b.check=function(){return"undefined"==typeof WebSocket||!("__initialize"in WebSocket)||!swfobject?!1:10<=swfobject.getFlashPlayerVersion().major};b.xdomainCheck=function(){return!0};"undefined"!=typeof window&&(WEB_SOCKET_DISABLE_AUTO_INITIALIZATION=!0);a.transports.push("flashsocket")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
if("undefined"!=typeof window)var swfobject=function(){function e(){if(!C){try{var a=k.getElementsByTagName("body")[0].appendChild(k.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}C=!0;for(var a=G.length,c=0;c<a;c++)G[c]()}}function a(a){C?a():G[G.length]=a}function b(a){if(typeof x.addEventListener!=q)x.addEventListener("load",a,!1);else if(typeof k.addEventListener!=q)k.addEventListener("load",a,!1);else if(typeof x.attachEvent!=q)v(x,"onload",a);else if("function"==typeof x.onload){var b=
x.onload;x.onload=function(){b();a()}}else x.onload=a}function c(){var a=k.getElementsByTagName("body")[0],b=k.createElement(t);b.setAttribute("type",r);var c=a.appendChild(b);if(c){var d=0;(function(){if(typeof c.GetVariable!=q){var f=c.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),h.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}else if(10>d){d++;setTimeout(arguments.callee,10);return}a.removeChild(b);c=null;g()})()}else g()}function g(){var a=A.length;if(0<a)for(var b=0;b<
a;b++){var c=A[b].id,e=A[b].callbackFn,g={success:!1,id:c};if(0<h.pv[0]){var k=u(c);if(k)if(w(A[b].swfVersion)&&!(h.wk&&312>h.wk))z(c,!0),e&&(g.success=!0,g.ref=f(c),e(g));else if(A[b].expressInstall&&d()){g={};g.data=A[b].expressInstall;g.width=k.getAttribute("width")||"0";g.height=k.getAttribute("height")||"0";k.getAttribute("class")&&(g.styleclass=k.getAttribute("class"));k.getAttribute("align")&&(g.align=k.getAttribute("align"));for(var N={},k=k.getElementsByTagName("param"),n=k.length,p=0;p<
n;p++)"movie"!=k[p].getAttribute("name").toLowerCase()&&(N[k[p].getAttribute("name")]=k[p].getAttribute("value"));l(g,N,c,e)}else m(k),e&&e(g)}else if(z(c,!0),e){if((c=f(c))&&typeof c.SetVariable!=q)g.success=!0,g.ref=c;e(g)}}}function f(a){var b=null;if((a=u(a))&&"OBJECT"==a.nodeName)typeof a.SetVariable!=q?b=a:(a=a.getElementsByTagName(t)[0])&&(b=a);return b}function d(){return!H&&w("6.0.65")&&(h.win||h.mac)&&!(h.wk&&312>h.wk)}function l(a,b,c,d){H=!0;K=d||null;O={success:!1,id:c};var f=u(c);if(f){"OBJECT"==
f.nodeName?(F=s(f),I=null):(F=f,I=c);a.id=P;if(typeof a.width==q||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==q||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";k.title=k.title.slice(0,47)+" - Flash Player Installation";d=h.ie&&h.win?["Active"].concat("").join("X"):"PlugIn";d="MMredirectURL="+x.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+k.title;b.flashvars=typeof b.flashvars!=q?b.flashvars+("&"+d):d;h.ie&&(h.win&&4!=
f.readyState)&&(d=k.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),f.parentNode.insertBefore(d,f),f.style.display="none",function(){4==f.readyState?f.parentNode.removeChild(f):setTimeout(arguments.callee,10)}());p(a,b,c)}}function m(a){if(h.ie&&h.win&&4!=a.readyState){var b=k.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(s(a),b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(s(a),
a)}function s(a){var b=k.createElement("div");if(h.win&&h.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(t)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function p(a,b,c){var d,f=u(c);if(h.wk&&312>h.wk)return d;if(f)if(typeof a.id==q&&(a.id=c),h.ie&&h.win){var e="",g;for(g in a)a[g]!=Object.prototype[g]&&("data"==g.toLowerCase()?b.movie=a[g]:"styleclass"==g.toLowerCase()?e+=
' class="'+a[g]+'"':"classid"!=g.toLowerCase()&&(e+=" "+g+'="'+a[g]+'"'));g="";for(var l in b)b[l]!=Object.prototype[l]&&(g+='<param name="'+l+'" value="'+b[l]+'" />');f.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+e+">"+g+"</object>";J[J.length]=a.id;d=u(a.id)}else{l=k.createElement(t);l.setAttribute("type",r);for(var m in a)a[m]!=Object.prototype[m]&&("styleclass"==m.toLowerCase()?l.setAttribute("class",a[m]):"classid"!=m.toLowerCase()&&l.setAttribute(m,a[m]));for(e in b)b[e]!=
Object.prototype[e]&&"movie"!=e.toLowerCase()&&(a=l,g=e,m=b[e],c=k.createElement("param"),c.setAttribute("name",g),c.setAttribute("value",m),a.appendChild(c));f.parentNode.replaceChild(l,f);d=l}return d}function n(a){var b=u(a);b&&"OBJECT"==b.nodeName&&(h.ie&&h.win?(b.style.display="none",function(){if(4==b.readyState){var c=u(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function u(a){var b=
null;try{b=k.getElementById(a)}catch(c){}return b}function v(a,b,c){a.attachEvent(b,c);E[E.length]=[a,b,c]}function w(a){var b=h.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function D(a,b,c,d){if(!h.ie||!h.mac){var f=k.getElementsByTagName("head")[0];if(f){c=c&&"string"==typeof c?c:"screen";d&&(L=y=null);if(!y||L!=c)d=k.createElement("style"),d.setAttribute("type","text/css"),
d.setAttribute("media",c),y=f.appendChild(d),h.ie&&(h.win&&typeof k.styleSheets!=q&&0<k.styleSheets.length)&&(y=k.styleSheets[k.styleSheets.length-1]),L=c;h.ie&&h.win?y&&typeof y.addRule==t&&y.addRule(a,b):y&&typeof k.createTextNode!=q&&y.appendChild(k.createTextNode(a+" {"+b+"}"))}}}function z(a,b){if(Q){var c=b?"visible":"hidden";C&&u(a)?u(a).style.visibility=c:D("#"+a,"visibility:"+c)}}function M(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=q?encodeURIComponent(a):a}var q=
"undefined",t="object",r="application/x-shockwave-flash",P="SWFObjectExprInst",x=window,k=document,B=navigator,R=!1,G=[function(){R?c():g()}],A=[],J=[],E=[],F,I,K,O,C=!1,H=!1,y,L,Q=!0,h=function(){var a=typeof k.getElementById!=q&&typeof k.getElementsByTagName!=q&&typeof k.createElement!=q,b=B.userAgent.toLowerCase(),c=B.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,f=!+"\v1",e=
[0,0,0],g=null;if(typeof B.plugins!=q&&typeof B.plugins["Shockwave Flash"]==t){if((g=B.plugins["Shockwave Flash"].description)&&!(typeof B.mimeTypes!=q&&B.mimeTypes[r]&&!B.mimeTypes[r].enabledPlugin))R=!0,f=!1,g=g.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),e[0]=parseInt(g.replace(/^(.*)\..*$/,"$1"),10),e[1]=parseInt(g.replace(/^.*\.(.*)\s.*$/,"$1"),10),e[2]=/[a-zA-Z]/.test(g)?parseInt(g.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof x[["Active"].concat("Object").join("X")]!=q)try{var l=new (window[["Active"].concat("Object").join("X")])("ShockwaveFlash.ShockwaveFlash");
if(l&&(g=l.GetVariable("$version")))f=!0,g=g.split(" ")[1].split(","),e=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)]}catch(m){}return{w3:a,pv:e,wk:b,ie:f,win:d,mac:c}}();(function(){h.w3&&((typeof k.readyState!=q&&"complete"==k.readyState||typeof k.readyState==q&&(k.getElementsByTagName("body")[0]||k.body))&&e(),C||(typeof k.addEventListener!=q&&k.addEventListener("DOMContentLoaded",e,!1),h.ie&&h.win&&(k.attachEvent("onreadystatechange",function(){"complete"==k.readyState&&(k.detachEvent("onreadystatechange",
arguments.callee),e())}),x==top&&function(){if(!C){try{k.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}e()}}()),h.wk&&function(){C||(/loaded|complete/.test(k.readyState)?e():setTimeout(arguments.callee,0))}(),b(e)))})();(function(){h.ie&&h.win&&window.attachEvent("onunload",function(){for(var a=E.length,b=0;b<a;b++)E[b][0].detachEvent(E[b][1],E[b][2]);a=J.length;for(b=0;b<a;b++)n(J[b]);for(var c in h)h[c]=null;h=null;for(var d in swfobject)swfobject[d]=null;swfobject=
null})})();return{registerObject:function(a,b,c,d){if(h.w3&&a&&b){var f={};f.id=a;f.swfVersion=b;f.expressInstall=c;f.callbackFn=d;A[A.length]=f;z(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(h.w3)return f(a)},embedSWF:function(b,c,f,e,g,m,k,n,r,s){var u={success:!1,id:c};h.w3&&!(h.wk&&312>h.wk)&&b&&c&&f&&e&&g?(z(c,!1),a(function(){f+="";e+="";var a={};if(r&&typeof r===t)for(var h in r)a[h]=r[h];a.data=b;a.width=f;a.height=e;h={};if(n&&typeof n===t)for(var v in n)h[v]=n[v];if(k&&
typeof k===t)for(var x in k)h.flashvars=typeof h.flashvars!=q?h.flashvars+("&"+x+"="+k[x]):x+"="+k[x];if(w(g))v=p(a,h,c),a.id==c&&z(c,!0),u.success=!0,u.ref=v;else{if(m&&d()){a.data=m;l(a,h,c,s);return}z(c,!0)}s&&s(u)})):s&&s(u)},switchOffAutoHideShow:function(){Q=!1},ua:h,getFlashPlayerVersion:function(){return{major:h.pv[0],minor:h.pv[1],release:h.pv[2]}},hasFlashPlayerVersion:w,createSWF:function(a,b,c){if(h.w3)return p(a,b,c)},showExpressInstall:function(a,b,c,f){h.w3&&d()&&l(a,b,c,f)},removeSWF:function(a){h.w3&&
n(a)},createCSS:function(a,b,c,d){h.w3&&D(a,b,c,d)},addDomLoadEvent:a,addLoadEvent:b,getQueryParamValue:function(a){var b=k.location.search||k.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return M(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return M(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(H){var a=u(P);a&&F&&(a.parentNode.replaceChild(F,a),I&&(z(I,!0),h.ie&&h.win&&(F.style.display="block")),
K&&K(O));H=!1}}}}();
(function(){if(!("undefined"==typeof window||window.WebSocket)){var e=window.console;if(!e||!e.log||!e.error)e={log:function(){},error:function(){}};swfobject.hasFlashPlayerVersion("10.0.0")?("file:"==location.protocol&&e.error("WARNING: web-socket-js doesn't work in file:///... URL unless you set Flash Security Settings properly. Open the page via Web server i.e. http://..."),WebSocket=function(a,b,c,e,f){var d=this;d.__id=WebSocket.__nextId++;WebSocket.__instances[d.__id]=d;d.readyState=WebSocket.CONNECTING;
d.bufferedAmount=0;d.__events={};b?"string"==typeof b&&(b=[b]):b=[];setTimeout(function(){WebSocket.__addTask(function(){WebSocket.__flash.create(d.__id,a,b,c||null,e||0,f||null)})},0)},WebSocket.prototype.send=function(a){if(this.readyState==WebSocket.CONNECTING)throw"INVALID_STATE_ERR: Web Socket connection has not been established";a=WebSocket.__flash.send(this.__id,encodeURIComponent(a));if(0>a)return!0;this.bufferedAmount+=a;return!1},WebSocket.prototype.close=function(){this.readyState==WebSocket.CLOSED||
this.readyState==WebSocket.CLOSING||(this.readyState=WebSocket.CLOSING,WebSocket.__flash.close(this.__id))},WebSocket.prototype.addEventListener=function(a,b,c){a in this.__events||(this.__events[a]=[]);this.__events[a].push(b)},WebSocket.prototype.removeEventListener=function(a,b,c){if(a in this.__events){a=this.__events[a];for(c=a.length-1;0<=c;--c)if(a[c]===b){a.splice(c,1);break}}},WebSocket.prototype.dispatchEvent=function(a){for(var b=this.__events[a.type]||[],c=0;c<b.length;++c)b[c](a);(b=
this["on"+a.type])&&b(a)},WebSocket.prototype.__handleEvent=function(a){"readyState"in a&&(this.readyState=a.readyState);"protocol"in a&&(this.protocol=a.protocol);if("open"==a.type||"error"==a.type)a=this.__createSimpleEvent(a.type);else if("close"==a.type)a=this.__createSimpleEvent("close");else if("message"==a.type)a=decodeURIComponent(a.message),a=this.__createMessageEvent("message",a);else throw"unknown event type: "+a.type;this.dispatchEvent(a)},WebSocket.prototype.__createSimpleEvent=function(a){if(document.createEvent&&
window.Event){var b=document.createEvent("Event");b.initEvent(a,!1,!1);return b}return{type:a,bubbles:!1,cancelable:!1}},WebSocket.prototype.__createMessageEvent=function(a,b){if(document.createEvent&&window.MessageEvent&&!window.opera){var c=document.createEvent("MessageEvent");c.initMessageEvent("message",!1,!1,b,null,null,window,null);return c}return{type:a,data:b,bubbles:!1,cancelable:!1}},WebSocket.CONNECTING=0,WebSocket.OPEN=1,WebSocket.CLOSING=2,WebSocket.CLOSED=3,WebSocket.__flash=null,WebSocket.__instances=
{},WebSocket.__tasks=[],WebSocket.__nextId=0,WebSocket.loadFlashPolicyFile=function(a){WebSocket.__addTask(function(){WebSocket.__flash.loadManualPolicyFile(a)})},WebSocket.__initialize=function(){if(!WebSocket.__flash)if(WebSocket.__swfLocation&&(window.WEB_SOCKET_SWF_LOCATION=WebSocket.__swfLocation),window.WEB_SOCKET_SWF_LOCATION){var a=document.createElement("div");a.id="webSocketContainer";a.style.position="absolute";WebSocket.__isFlashLite()?(a.style.left="0px",a.style.top="0px"):(a.style.left=
"-100px",a.style.top="-100px");var b=document.createElement("div");b.id="webSocketFlash";a.appendChild(b);document.body.appendChild(a);swfobject.embedSWF(WEB_SOCKET_SWF_LOCATION,"webSocketFlash","1","1","10.0.0",null,null,{hasPriority:!0,swliveconnect:!0,allowScriptAccess:"always"},null,function(a){a.success||e.error("[WebSocket] swfobject.embedSWF failed")})}else e.error("[WebSocket] set WEB_SOCKET_SWF_LOCATION to location of WebSocketMain.swf")},WebSocket.__onFlashInitialized=function(){setTimeout(function(){WebSocket.__flash=
document.getElementById("webSocketFlash");WebSocket.__flash.setCallerUrl(location.href);WebSocket.__flash.setDebug(!!window.WEB_SOCKET_DEBUG);for(var a=0;a<WebSocket.__tasks.length;++a)WebSocket.__tasks[a]();WebSocket.__tasks=[]},0)},WebSocket.__onFlashEvent=function(){setTimeout(function(){try{for(var a=WebSocket.__flash.receiveEvents(),b=0;b<a.length;++b)WebSocket.__instances[a[b].webSocketId].__handleEvent(a[b])}catch(c){e.error(c)}},0);return!0},WebSocket.__log=function(a){e.log(decodeURIComponent(a))},
WebSocket.__error=function(a){e.error(decodeURIComponent(a))},WebSocket.__addTask=function(a){WebSocket.__flash?a():WebSocket.__tasks.push(a)},WebSocket.__isFlashLite=function(){if(!window.navigator||!window.navigator.mimeTypes)return!1;var a=window.navigator.mimeTypes["application/x-shockwave-flash"];return!a||!a.enabledPlugin||!a.enabledPlugin.filename?!1:a.enabledPlugin.filename.match(/flashlite/i)?!0:!1},window.WEB_SOCKET_DISABLE_AUTO_INITIALIZATION||(window.addEventListener?window.addEventListener("load",
function(){WebSocket.__initialize()},!1):window.attachEvent("onload",function(){WebSocket.__initialize()}))):e.error("Flash Player >= 10.0.0 is required.")}})();
(function(e,a,b){function c(b){b&&(a.Transport.apply(this,arguments),this.sendBuffer=[])}function g(){}e.XHR=c;a.util.inherit(c,a.Transport);c.prototype.open=function(){this.socket.setBuffer(!1);this.onOpen();this.get();this.setCloseTimeout();return this};c.prototype.payload=function(b){for(var c=[],e=0,g=b.length;e<g;e++)c.push(a.parser.encodePacket(b[e]));this.send(a.parser.encodePayload(c))};c.prototype.send=function(a){this.post(a);return this};c.prototype.post=function(a){function c(){if(4==
this.readyState)if(this.onreadystatechange=g,m.posting=!1,200==this.status)m.socket.setBuffer(!1);else m.onClose()}function e(){this.onload=g;m.socket.setBuffer(!1)}var m=this;this.socket.setBuffer(!0);this.sendXHR=this.request("POST");b.XDomainRequest&&this.sendXHR instanceof XDomainRequest?this.sendXHR.onload=this.sendXHR.onerror=e:this.sendXHR.onreadystatechange=c;this.sendXHR.send(a)};c.prototype.close=function(){this.onClose();return this};c.prototype.request=function(b){var c=a.util.request(this.socket.isXDomain()),
e=a.util.query(this.socket.options.query,"t="+ +new Date);c.open(b||"GET",this.prepareUrl()+e,!0);if("POST"==b)try{c.setRequestHeader?c.setRequestHeader("Content-type","text/plain;charset=UTF-8"):c.contentType="text/plain"}catch(g){}return c};c.prototype.scheme=function(){return this.socket.options.secure?"https":"http"};c.check=function(b,c){try{if(a.util.request(c))return!0}catch(e){}return!1};c.xdomainCheck=function(){return c.check(null,!0)}})("undefined"!=typeof io?io.Transport:module.exports,
"undefined"!=typeof io?io:module.parent.exports,this);
(function(e,a){function b(b){a.Transport.XHR.apply(this,arguments)}e.htmlfile=b;a.util.inherit(b,a.Transport.XHR);b.prototype.name="htmlfile";b.prototype.get=function(){this.doc=new (window[["Active"].concat("Object").join("X")])("htmlfile");this.doc.open();this.doc.write("<html></html>");this.doc.close();this.doc.parentWindow.s=this;var b=this.doc.createElement("div");b.className="socketio";this.doc.body.appendChild(b);this.iframe=this.doc.createElement("iframe");b.appendChild(this.iframe);var e=
this,b=a.util.query(this.socket.options.query,"t="+ +new Date);this.iframe.src=this.prepareUrl()+b;a.util.on(window,"unload",function(){e.destroy()})};b.prototype._=function(a,b){this.onData(a);try{var f=b.getElementsByTagName("script")[0];f.parentNode.removeChild(f)}catch(d){}};b.prototype.destroy=function(){if(this.iframe){try{this.iframe.src="about:blank"}catch(a){}this.doc=null;this.iframe.parentNode.removeChild(this.iframe);this.iframe=null;CollectGarbage()}};b.prototype.close=function(){this.destroy();
return a.Transport.XHR.prototype.close.call(this)};b.check=function(){if("undefined"!=typeof window&&["Active"].concat("Object").join("X")in window)try{return new (window[["Active"].concat("Object").join("X")])("htmlfile")&&a.Transport.XHR.check()}catch(b){}return!1};b.xdomainCheck=function(){return!1};a.transports.push("htmlfile")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports);
(function(e,a,b){function c(){a.Transport.XHR.apply(this,arguments)}function g(){}e["xhr-polling"]=c;a.util.inherit(c,a.Transport.XHR);a.util.merge(c,a.Transport.XHR);c.prototype.name="xhr-polling";c.prototype.open=function(){a.Transport.XHR.prototype.open.call(this);return!1};c.prototype.get=function(){function a(){if(4==this.readyState)if(this.onreadystatechange=g,200==this.status)m.onData(this.responseText),m.get();else m.onClose()}function c(){this.onerror=this.onload=g;m.onData(this.responseText);
m.get()}function e(){m.onClose()}if(this.open){var m=this;this.xhr=this.request();b.XDomainRequest&&this.xhr instanceof XDomainRequest?(this.xhr.onload=c,this.xhr.onerror=e):this.xhr.onreadystatechange=a;this.xhr.send(null)}};c.prototype.onClose=function(){a.Transport.XHR.prototype.onClose.call(this);if(this.xhr){this.xhr.onreadystatechange=this.xhr.onload=this.xhr.onerror=g;try{this.xhr.abort()}catch(b){}this.xhr=null}};c.prototype.ready=function(b,c){var e=this;a.util.defer(function(){c.call(e)})};
a.transports.push("xhr-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
(function(e,a,b){function c(b){a.Transport["xhr-polling"].apply(this,arguments);this.index=a.j.length;var c=this;a.j.push(function(a){c._(a)})}var g=b.document&&"MozAppearance"in b.document.documentElement.style;e["jsonp-polling"]=c;a.util.inherit(c,a.Transport["xhr-polling"]);c.prototype.name="jsonp-polling";c.prototype.post=function(b){function c(){e();g.socket.setBuffer(!1)}function e(){g.iframe&&g.form.removeChild(g.iframe);try{v=document.createElement('<iframe name="'+g.iframeId+'">')}catch(a){v=
document.createElement("iframe"),v.name=g.iframeId}v.id=g.iframeId;g.form.appendChild(v);g.iframe=v}var g=this,s=a.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);if(!this.form){var p=document.createElement("form"),n=document.createElement("textarea"),u=this.iframeId="socketio_iframe_"+this.index,v;p.className="socketio";p.style.position="absolute";p.style.top="-1000px";p.style.left="-1000px";p.target=u;p.method="POST";p.setAttribute("accept-charset","utf-8");n.name="d";p.appendChild(n);
document.body.appendChild(p);this.form=p;this.area=n}this.form.action=this.prepareUrl()+s;e();this.area.value=a.JSON.stringify(b);try{this.form.submit()}catch(w){}this.iframe.attachEvent?v.onreadystatechange=function(){"complete"==g.iframe.readyState&&c()}:this.iframe.onload=c;this.socket.setBuffer(!0)};c.prototype.get=function(){var b=this,c=document.createElement("script"),e=a.util.query(this.socket.options.query,"t="+ +new Date+"&i="+this.index);this.script&&(this.script.parentNode.removeChild(this.script),
this.script=null);c.async=!0;c.src=this.prepareUrl()+e;c.onerror=function(){b.onClose()};e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(c,e);this.script=c;g&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};c.prototype._=function(a){this.onData(a);this.open&&this.get();return this};c.prototype.ready=function(b,c){var e=this;if(!g)return c.call(this);a.util.load(function(){c.call(e)})};c.check=function(){return"document"in
b};c.xdomainCheck=function(){return!0};a.transports.push("jsonp-polling")})("undefined"!=typeof io?io.Transport:module.exports,"undefined"!=typeof io?io:module.parent.exports,this);
